### PR TITLE
Adding contextual compression with an LLMChainExtractor

### PR DESCRIPTION
**Pull request by joseanu**
Implementation of LLMChainExtractor functionality.

### CODE REVIEW

**Review by dev2049 — APPROVED** [review]
looks great to me! do we do any sort of integration testing in js @nfcampos ?

**Comment by joseanu** [comment]
> looks great to me! do we do any sort of integration testing in js?

It doesn’t do any new integration with an API.
Or maybe I don't understand you question?

**Comment by nfcampos** [comment]
Thanks!

**Comment by joseanu** [comment]
What happened? I get no build errors.

**Comment by nfcampos** [comment]
@joseanu just something that has changed in latest master, no worries I've updated the PR now, should be good

**Comment by joseanu** [comment]
💪 This is my first open source contribution

**Pull request merged**
