### PR TITLE
Upgrade Chroma to 1.5.2

### LINKED ISSUE #1481: queryEmbeddings and queryTexts cannot both be undefined on Chromadb 1.5.1
Updated to version `0.87` and got the Chromadb `1.5.1` update from `1.5.0`.
[This commit](https://github.com/chroma-core/chroma/commit/565f2e4fb84cf92f5cf57df001edd90e3389ded8) changing to use `camelCase` broke compatibility. When using the query I get the error

```
queryEmbeddings and queryTexts cannot both be undefined
```

### PR DESCRIPTION
**Pull request by Russell-Pollari**
Upgrade chroma to 1.5.2

chomadb@1.5.1 introduces a breaking change, switching from `snake_case` to `camelCase` arguments in `collection.query`. 
chromadb@1.5.2 fixes a type error introduced in 1.5.0

Fixes #1481 

`$ yarn test:single langchain/src/vectorstores/tests/chroma.test.ts ` passes

### CODE REVIEW

**Comment by jeffchuber** [comment]
+1 ! thanks @Russell-Pollari

**Comment by Russell-Pollari** [comment]
FYI - this error:
`langchain:build: src/vectorstores/chroma.ts(142,9): error TS2322: Type 'number[]' is not assignable to type 'number'.

is due to a bug in chromadb, addressed here: https://github.com/chroma-core/chroma/pull/661

So may need to wait until the next release of chromadb

**Comment by jeffchuber** [comment]
@Russell-Pollari got it. i think we can cut a off-cycle release for this. let me look into it.

**Comment by jeffchuber** [comment]
@Russell-Pollari `1.5.2` now released https://www.npmjs.com/package/chromadb - can you give this a go?

**Comment by Russell-Pollari** [comment]
type error is gone with 1.5.2

**Comment by jacoblee93** [comment]
Bumped with the peer dependency as well - can cut a release tonight if people want, or just wait until Monday?

**Comment by jacoblee93** [comment]
Just released 0.0.90 with the fix!

**Comment by jeffchuber** [comment]
thank you everyone!

**Pull request merged**
