### PR TITLE
feat: getDefaultOutputParser fields

### PR DESCRIPTION
**Pull request by jacobrosenthal**
I have an issue with the new outputparser refactors. you cant take in Final Tool name as a variable to getDefaultOutputParser (which is abstract so has to be there)

### CODE REVIEW

**Review by hwchase17 — APPROVED** [review]
conceptually seems great to me!

**Comment by jacobrosenthal** [comment]
The other use case for this is to make it a fixing parser, and give down the llm in the fields

**Comment by jacobrosenthal** [comment]
As a bonus, this allows  putting Format instructions inside the output parser where they probably belong.

also refactoring out allowedTools which is clunky now

You can throw that top commit out, I dont care either way, just wanted to point at it. It needs the `ZeroShotAgent.deserializer` to be fixed if you want to keep it (presuming that doesnt break backcompat or whatever)

**Review by nfcampos — APPROVED** [review]

**Comment by nfcampos** [comment]
Thanks!

**Pull request merged**
