### PR TITLE
Allow passing options to LLM chains inside MultiRetrievalQAChain and MultiPromptChain.

### PR DESCRIPTION
**Pull request by ppramesi**
Changed MultiRetrievalQAChain.fromRetrievers parameter into one option. Added multiRetrievalChainOpts and retrievalQAChainOpts into the fromRetrievers's parameters, so we can pass options to the multi retrieval chain and retrieval QA chains (so e.g. we can pass returnSourceDocuments to the RetrievalQAChain).

Same with MultiPromptChain.fromPrompts.

### CODE REVIEW

**Comment by jacoblee93** [comment]
So of course this will break anyone currently using this, but looks like this was a very recent addition anyway - will leave it up to @nfcampos

**Comment by jacoblee93** [comment]
So I think the best option since the behavior isn't that different and it's now been out for a little while is to just deprecate the old methods and have them wrap new ones, `fromLLMAndPrompts` and `fromLLMAndRetrievers`.

Does that sound ok to you @ppramesi?

**Comment by ppramesi** [comment]
> So I think the best option since the behavior isn't that different and it's now been out for a little while is to just deprecate the old methods and have them wrap new ones, `fromLLMAndPrompts` and `fromLLMAndRetrievers`.
> 
> Does that sound ok to you @ppramesi?

Sounds good to me

**Comment by jacoblee93** [comment]
Alright cool, it'll be part of tomorrow's release :)

**Pull request merged**
