### PR TITLE
feat: ChatOpenAi support tokenUsage

### PR DESCRIPTION
**Pull request by jacobrosenthal**
Unless it wasnt there for some other reason

### CODE REVIEW

**Comment by nfcampos** [comment]
Thanks. Could you add something about this to one of the existing integration tests for chatopenai?

**Review by hwchase17 — APPROVED** [review]
yay! this is great

**Comment by h4ck4life** [comment]
Nice! Thank you. What release version in npm this changes will be available? Tried with 0.0.36 , the callback return `undefined` for `llmOutput` object.

**Comment by nfcampos** [comment]
@h4ck4life this was released in 0.0.36, can you share a snippet of your code so I can understand why you might not be seeing it?

**Comment by h4ck4life** [comment]
Here is my code snippet. I'm trying to get the token via callbacks but getting `undefined`

```ts
let tokenUsage = {
    completionTokens: 0,
    promptTokens: 0,
    totalTokens: 0,
};

/* Initialize the LLM to use to answer the question */
const model = new OpenAI({
    temperature: 0.4,
    topP: 1.0,
    maxTokens: 250,
    modelName: "gpt-3.5-turbo",
    maxRetries: 3,
    streaming: false,
    callbackManager: CallbackManager.fromHandlers({
        async handleLLMEnd(output: LLMResult) {
            tokenUsage = output.llmOutput?.tokenUsage;
        },
    }),
});

// Load the vector store from the same directory
const vectorStore = await HNSWLib.load(
    "vector",
    new OpenAIEmbeddings()
);

/* Create the chain */
const chain = ChatVectorDBQAChain.fromLLM(model, vectorStore);

const askChatGPT = async (question: string, chatHistory: string): Promise<string> => {
    const res = await chain.call({
        question: question,
        chat_history: chatHistory,
    });
    console.log(tokenUsage);
    return res.text;
}

export { askChatGPT };
```

**Comment by ElektrikSpark** [comment]
I am trying to track token usage in this way as well, but I am also getting `undefined`. Any luck figuring this out? @h4ck4life

**Comment by h4ck4life** [comment]
Thanks @nfcampos . Now I can see the token information in the callback by using `ChatOpenAI` instead in `OpenAI` . Fyi @ElektrikSpark 

```ts
const model = new ChatOpenAI({
    cache: false,
    temperature: tune.temperature,
    topP: tune.topP,
    maxTokens: tune.maxTokens,
    modelName: "gpt-3.5-turbo",
    maxRetries: 3,
    streaming: false,
    callbackManager: CallbackManager.fromHandlers({
        async handleLLMEnd(output: LLMResult) {
            tokenUsage = output.llmOutput?.tokenUsage;
            console.log(`Token usage: ${JSON.stringify(tokenUsage)}`);
        },
    }),
});
```

**Comment by nfcampos** [comment]
@YikaJ would that be because you're using it in `streaming` mode? This is not sent by openai in streaming mode afaik

**Comment by leohxj** [comment]
llmOutput got `undefined` in version 0.0.107

**Pull request merged**
