### PR TITLE
feat: add figma loader

### PR DESCRIPTION
**Pull request by munkhorgil**
PR for #1132

### CODE REVIEW

**Comment by munkhorgil** [comment]
I would love to contribute more. Please let me know if I am missing anything.

**Comment by munkhorgil** [comment]
Hey @nfcampos could you have a look at this PR?

**Comment by nfcampos** [comment]
Hi @munkhorgil thanks for this, could you add a page in the docs directory for this, and an example of how to use, you can look at one of the other loaders docs for inspiration

**Comment by munkhorgil** [comment]
> Hi @munkhorgil thanks for this, could you add a page in the docs directory for this, and an example of how to use, you can look at one of the other loaders docs for inspiration

Should be good to go now :)

**Comment by munkhorgil** [comment]
Hey, @jacoblee93 Could you have a look at this one?

**Comment by jacoblee93** [comment]
Thank you very much! A few small updates but looks great. Will be part of today's release!

**Pull request merged**
