### PR TITLE
add typeorm vectorstore

### PR DESCRIPTION
**Pull request by MaximeThoonsen**
# add typeorm vectorstore

I'm doing this separate PR from the [orignal PR](https://github.com/hwchase17/langchainjs/pull/1345) to only add Typeorm vectorstore.

### CODE REVIEW

**Comment by jacoblee93** [comment]
Thanks! Will look tomorrow.

**Comment by jacoblee93** [comment]
Hey @MaximeThoonsen, I'm very sorry about the delay here - will aim to get this looked at and hopefully merged tomorrow.

**Comment by jacoblee93** [comment]
Thank you @MaximeThoonsen! Pushed some small build fixes and docs fixes, but should be good to go with the next release :)

**Comment by jacoblee93** [comment]
Thank you for your patience!

**Comment by MaximeThoonsen** [comment]
Hey @jacoblee93. Thanks a lot for your help!
I'll ping you on the other PR for the other changes I wanted to make on Document class

**Comment by roselle11111** [comment]
Any update on this? i got the following error when using typeorm langchain vectorestore.

"DatabaseErrorException: ERROR: column "embedding" is of type vector but expression is of type text; Hint: You will need to rewrite or cast the expression"

**Pull request merged**
