### PR TITLE
Docstore updates - change base class and add GoogleCloudStorage Docstore

### PR DESCRIPTION
**Pull request by afirstenberg**
Prerequisite for #1532 

This changes the Docstore base class to make the methods asynchronous, and adds a new Synchronous base class for the in-memory docstore to use.
Additionally, this new Docstore base class is the basis for a Google Cloud Storage (GCS) implementation.

### CODE REVIEW

**Review by nfcampos — APPROVED** [review]
Thanks, LGTM

**Comment by afirstenberg** [comment]
Just to make sure I followed, @nfcampos - we're getting rid of the docstore directory and, essentially, moving everything from it to stores/doc?

**Comment by nfcampos** [comment]
Yes exactly. It's something I've had in mind to do for a while, and now that you're introducing the first implementation of doc store (other than in memory) is the best time to do it. The other change removing the synchronous base class is just to make it less likely people open PRs implementing more synchronous doc stores, which we don't want

**Comment by afirstenberg** [comment]
Got it, and looks good. Thanks!

**Pull request merged**
