### PR TITLE
[Doc][QuickStart] Move steps forget to move

### PR DESCRIPTION
**Pull request by killinsun**
## Background

In the past, [the quickstart tutorial](https://js.langchain.com/docs/getting-started/guide-chat#model--prompt--llmchain) has a step to explain `ConversationChain` https://github.com/hwchase17/langchainjs/commit/2b54606c0ff2f46704a3aef8f0ebb05f6e67d216

However, the PR above looks to have forgotten to move some explanations, so it causes confusion.
https://github.com/hwchase17/langchainjs/issues/1161

スクリーンショット 2023-05-09 0 28 06

### CODE REVIEW

**Comment by nfcampos** [comment]
@killinsun Thanks for this! That is indeed a mistake, thanks for catching that. If instead you move the lines youre removing to right before `## Streaming` then it will all make sense I think. This was broken accidentally in a previous PR

**Comment by killinsun** [comment]
@nfcampos 
Thank you for the  quick reply!
I got it!
I'll push a changes later.

**Comment by killinsun** [comment]
@nfcampos 
I pushed CR fixes 🙇  Please check it when you have time.

**Comment by nfcampos** [comment]
Great, thanks!

**Pull request merged**
