### PR TITLE
feat: basic unstructured loader for langchainjs

### PR DESCRIPTION
**Pull request by MthwRobinson**
### Summary

Implements a basic Unstructured file loader for langchainjs. The loader posts the specified file to the Unstructured REST API. The API is not public yet, but you can run it locally using the instructions [here](https://github.com/Unstructured-IO/pipeline-general#see-the-unstructured-quick-start-for-the-many-os-dependencies-that-are-required-if-the-ability-to-process-all-file-types-is-desired). The test is disabled temporarily, but once we have a hosted API for the test to hit I can add in a PR to enable it.

Adds `node-fetch` and `form-data` as dependencies. Couldn't figure out how to get the `mixed/multipart-form` post to work without those, but maybe someone who's better than me at node can suggest an alternative :)

### Testing

- Install the Unstructured API locally using the instructions  [here](https://github.com/Unstructured-IO/pipeline-general#see-the-unstructured-quick-start-for-the-many-os-dependencies-that-are-required-if-the-ability-to-process-all-file-types-is-desired).
- Run `make run-web-app`
- Uncomment the code in `langchain/src/document_loaders/tests/unstructured.test.ts`
- Run `yarn test`. The tests should pass and you should see a `200` in the logs for the Unstructured API.

### CODE REVIEW

**Comment by nfcampos** [comment]
@MthwRobinson thanks for this! I'll have a look at removing the node-fetch dependency, I think there is a way of doing it without it

**Comment by nfcampos** [comment]
@MthwRobinson getting the following issue running this locally after converting it to use native `fetch` available in Node 16 onwards (which is what we support)

Screenshot 2023-03-03 at 14 14 51

Will push my changes to a branch so you can see/try

**Comment by nfcampos** [comment]
Changes here https://github.com/Unstructured-IO/langchainjs/compare/feat/unstructured-loader...hwchase17:langchainjs:nc/unstructured?expand=1

Any ideas let me know

**Comment by nfcampos** [comment]
Ah, in that branch getting this error instead 

```
INFO:     127.0.0.1:63419 - "POST /general/v0.0.4/general HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/nuno/.pyenv/versions/unstructured/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/nuno/.pyenv/versions/unstructured/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Users/nuno/.pyenv/versions/unstructured/lib/python3.8/site-packages/fastapi/applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/nuno/.pyenv/versions/unstructured/lib/python3.8/site-packages/starlette/applications.py", line 118, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/nuno/.pyenv/versions/unstructured/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/nuno/.pyenv/versions/unstructured/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/nuno/.pyenv/versions/unstructured/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/nuno/.pyenv/versions/unstructured/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/nuno/.pyenv/versions/unstructured/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/nuno/.pyenv/versions/unstructured/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/nuno/.pyenv/versions/unstructured/lib/python3.8/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/Users/nuno/.pyenv/versions/unstructured/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/nuno/.pyenv/versions/unstructured/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/Users/nuno/.pyenv/versions/unstructured/lib/python3.8/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/Users/nuno/.pyenv/versions/unstructured/lib/python3.8/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/nuno/.pyenv/versions/unstructured/lib/python3.8/site-packages/slowapi/extension.py", line 729, in async_wrapper
    response = await func(*args, **kwargs)  # type: ignore
  File "/Users/nuno/dev/unstructured-pipeline-general/./prepline_general/api/general.py", line 168, in pipeline_1
    response = pipeline_api(
  File "/Users/nuno/dev/unstructured-pipeline-general/./prepline_general/api/general.py", line 52, in pipeline_api
    elements = partition(filename=temp_file.name)
  File "/Users/nuno/.pyenv/versions/unstructured/lib/python3.8/site-packages/unstructured/partition/auto.py", line 69, in partition
    raise ValueError(f"{msg}. File type not support in partition.")
ValueError: Invalid file /var/folders/s_/r3cdpdn51ks9bw89jryhr08w0000gn/T/tmpo6z4is5k. File type not support in partition.```

**Comment by MthwRobinson** [comment]
@nfcampos - Give it a try on [this branch](https://github.com/Unstructured-IO/pipeline-general/tree/fix/pass-in-filename). Added in a quick fix that we'll need to clean up, but you should be able to test against that now.

cc: @LaverdeS

**Comment by nfcampos** [comment]
@MthwRobinson it works for me now, pushed some changes to my branch above, do you want me to combine it with yours?

**Comment by MthwRobinson** [comment]
@nfcampos - Yeah do you want to merge your branch into this one?

**Comment by nfcampos** [comment]
Great! When would we want to merge this? Given the API isn't public yet

**Comment by MthwRobinson** [comment]
Thanks for all the help! We should have the container ready sometime next week, I think it makes sense to hold on merging til then. @LaverdeS is working on that right now. We'll keep in touch on the status!

**Comment by LaverdeS** [comment]
Hey guys. Unstructured's `pipeline-general` has all the fixes now in this branch. You can tryout the API running the target `make run-web-app` and parse your `.txt` files and the other 8 doc-types 🙌🏼. Thank you for your contributions!

**Pull request merged**
