### PR TITLE
fixed filter to check for empty object and undefined

### PR DESCRIPTION
**Pull request by ElektrikSpark**
Issue #441 

Right now on similaritySearch an empty object is being passed in by default `filter: object = {}`. I opted to expand the validation to check for an empty object as well as undefined and keep the functionality the same.

We could change similaritySearchVectorWithScore from `filter?: object` to `filter: object = {}` to mimic `similaritySearch` and `similaritySearchWithScore` and remove the undefined checks.

### CODE REVIEW

**Comment by nfcampos** [comment]
@ElektrikSpark thanks. Yea my preference would be just remove the default value in the base class method, as that would eg allow people to set a default filter when instantiating (this.filter) and then disable it by passing an empty object on a call to similaritySearchVectorWithScore

**Comment by ElektrikSpark** [comment]
@nfcampos Sounds good. I removed the default value for filter, and to get around the `default-param-last` linting rule, and not break all the similaritySearch calls, I got rid of the default value of 4 for k on `similaritySearch`. We were setting a default value of k = 4 at the class level.

**Comment by nfcampos** [comment]
Or we can give the filter a default value of undefined? @ElektrikSpark

**Comment by ElektrikSpark** [comment]
Changed it to:
```
k = 4,
filter: object | undefined = undefined
```

**Pull request merged**
