### PR TITLE
Local embeddings function with Transformer.js API (extends #2267)

### PR DESCRIPTION
**Pull request by jacoblee93**
Extends #2267 with integration test

### CODE REVIEW

**Comment by jacoblee93** [comment]
@l4b4r4b4b4 I get this when running the integration test:

Screenshot 2023-08-17 at 2 50 25 PM

How are you running this?

**Comment by Durisvk** [comment]
Hey @jacoblee93 the solution was to share Float32Array between jest isolated contexts:
https://github.com/hwchase17/langchainjs/pull/2487

It's the least hacky solution my research could come up with

**Comment by Durisvk** [comment]
I am not sure how much you guys believe in simplicity vs customizability but I'd at least add the possibility to pass any `transformer.js` options as a `transformerJsOptions: {...}` object into the `HuggingFaceTransformersEmbeddings` class so that we hide extra complexity + allow extra customizability for super users.

**Comment by l4b4r4b4b4** [comment]
I actually solved it completely differently, by using LocalAI served local embeddings with OpenAI API.

**Comment by l4b4r4b4b4** [comment]
> I am not sure how much you guys believe in simplicity vs customizability but I'd at least add the possibility to pass any `transformer.js` options as a `transformerJsOptions: {...}` object into the `HuggingFaceTransformersEmbeddings` class so that we hide extra complexity under an optional object + allow extra customizability for super users.

I actually solved it completely differently, by using [LocalAIs](https://localai.io/) local embeddings served with OpenAI API. This way I cAn serve all the embeddings from huggingface in a seperate scalable micro-service.

**Comment by Durisvk** [comment]
> > I am not sure how much you guys believe in simplicity vs customizability but I'd at least add the possibility to pass any `transformer.js` options as a `transformerJsOptions: {...}` object into the `HuggingFaceTransformersEmbeddings` class so that we hide extra complexity under an optional object + allow extra customizability for super users.
> 
> I actually solved it completely differently, by using [LocalAIs](https://localai.io/) local embeddings served with OpenAI API. This way I cAn serve all the embeddings from huggingface in a seperate scalable micro-service and simply have to give a different base_url to the OpenAI langchain components.

@l4b4r4b4b4 This is the first time I'm seeing the [LocalAIs](https://localai.io/). Does it support all huggingface hosted models?

**Pull request closed without merging**
