### PR TITLE
test: test for agent using chatopenai -- broken

### PR DESCRIPTION
**Pull request by jacobrosenthal**
Trying to write a more complicated test, but couldnt get this simpler one to work and I dont think theres other agent tests with chatopen. Some tooling error hopefully someone else can understand

```
(node:1337224) ExperimentalWarning: VM Modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
 FAIL  src/agents/tests/agent.int.test.ts (7.04 s)
  ✕ Run agent locally with ChatOpenAI (1905 ms)
  ○ skipped Run agent from hub
  ○ skipped Run agent locally with OpenAI

  ● Run agent locally with ChatOpenAI

    Must use import to load ES Module: /home/jacob/z/langchainjs/node_modules/undici/lib/llhttp/llhttp.wasm

      at Runtime.requireModule (../node_modules/jest-runtime/build/index.js:841:21)
      at lazyllhttp (../node_modules/undici/lib/client.js:352:55)
      at Object.<anonymous> (../node_modules/undici/lib/client.js:414:21)
      at Object.<anonymous> (../node_modules/undici/index.js:3:16)

  ● Run agent locally with ChatOpenAI

    TypeError: fetch failed

      36 |   async _call(input: string) {
      37 |     const { getJson } = await SerpAPI.imports();
    > 38 |     const res = await getJson("google", {
         |                 ^
      39 |       ...this.params,
      40 |       api_key: this.key,
      41 |       q: input,

      at Object.fetch (../node_modules/undici/index.js:109:13)
      at Object.execute (../node_modules/serpapi/esm/src/utils.js:86:12)
      at getJson (../node_modules/serpapi/esm/src/serpapi.js:58:22)
      at SerpAPI._call (src/agents/tools/serpapi.ts:38:17)
      at SerpAPI.call (src/agents/tools/base.ts:31:16)
      at AgentExecutor._call (src/agents/executor.ts:95:11)
      at AgentExecutor.call (src/chains/base.ts:94:22)
      at Object.<anonymous> (src/agents/tests/agent.int.test.ts:62:18)

    Cause:
    Must use import to load ES Module: /home/jacob/z/langchainjs/node_modules/undici/lib/llhttp/llhttp.wasm

      at Runtime.requireModule (../node_modules/jest-runtime/build/index.js:841:21)
      at lazyllhttp (../node_modules/undici/lib/client.js:352:55)
      at Object.<anonymous> (../node_modules/undici/lib/client.js:414:21)
      at Object.<anonymous> (../node_modules/undici/index.js:3:16)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 2 skipped, 3 total
Snapshots:   0 total
Time:        7.138 s
Ran all test suites matching /agents\/tests\/agent/i.
Jest did not exit one second after the test run has completed.

'This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

### CODE REVIEW

**Comment by nfcampos** [comment]
I think with chat models you want to use either `chat-zero-shot-react-description` or `chat-conversational-react-description`. Other agents aren't designed for chat models, and may or may not work properly with them

**Comment by nfcampos** [comment]
@jacobrosenthal that particular issue in your logs above looks like what happens when `jest` for some reason forgets to apply the config. We have a command to run a single test, which might be what you're after `yarn run test:single src/agents/tests/agent.int.test.ts`

**Comment by jacobrosenthal** [comment]
Well I wrote one that is
https://github.com/hwchase17/langchainjs/pull/463

hence trying to test this in isolation
This IS the output when run with `yarn run test:single src/agents/tests/agent.int.test.ts`

**Comment by jacobrosenthal** [comment]
Heh, thanks :) I know how to make examples

I just wanted this open so we could discuss a larger solution. Im glad you see the conflict now

**Comment by nfcampos** [comment]
fyi ive merged the fix for this now, so if you rebase and re-run the test it should pass?

**Comment by jacobrosenthal** [comment]
Yes this fixes it, but I dont need this test then :) Moving this test back into my other pr

**Comment by nfcampos** [comment]
Cool it served its purpose

**Pull request closed without merging**
