### PR TITLE
Allow passing k number of documents to retrieve by ParentDocumentRetriever

### PR DESCRIPTION
**Pull request by karol-f**
When using `ParentDocumentRetriever`, searching for more documents in VectorStore is sometimes desired (especially when using LLM model with a bigger context window like GPT-4). This PR allows for adding such param (optional), so it can be used while searching vector store.

### CODE REVIEW

**Comment by jacoblee93** [comment]
Fantastic, thank you!

Let's update the docs as well - I can do so later if you don't have time.

**Comment by karol-f** [comment]
> Let's update the docs as well - I can do so later if you don't have time.

I've altered docs a bit - feel free to change it the way you like. Thank you.

**Comment by jacoblee93** [comment]
Renamed to `childK` to be more specific, but looks great! Will merge tonight.

**Comment by jacoblee93** [comment]
Thank you!

**Pull request merged**
