### PR TITLE
[FIX] s3loader credential interface

### PR DESCRIPTION
**Pull request by QasimRRizvi**
Fixes #[1460](https://github.com/hwchase17/langchainjs/issues/1460)

### CODE REVIEW

**Comment by jacoblee93** [comment]
This has been broken the whole time?

**Comment by jacoblee93** [comment]
Ok, either syntax seems to work - updating with backwards compatibility in mind for those folks using the old syntax.

**Comment by QasimRRizvi** [comment]
> patibility in mind for those folks using t

Yes it was, last time when I was using this I created patch for myself but I saw someother are facing the same issue so I decided to solve it.

**Comment by jacoblee93** [comment]
Thanks again and sorry about the wait! Had an issue with the mocks.

**Pull request merged**
