### PR TITLE
hnswlib: Throw error in index getter to dedupe code and have safer usage

### PR DESCRIPTION
**Pull request by micahriggan**
Feel free to close, but seems like we can provide safer access to .index with a getter that throws if it hasn't been init'd 

Also added a static method to init the HNSW Lib so we don't have to dupe the error handling each time

Oh yeah, thanks for making this, super cool

### CODE REVIEW

**Comment by sullivan-sean** [comment]
Great call! This cleans things up nicely.

**Comment by nfcampos** [comment]
Another option would be to make the index property private, if you need access to it you can always create the instance with an index created outside?

**Comment by micahriggan** [comment]
Yeah you could make it private, and you could use 

```HNSWLib.getHierarchicalNSW(args)``` in the other files instead of accessing index. You might have to re-init the index that way though. I only noticed 2 places that were external to this file accessing the index property, but I didn't dig into whether they relied on it being initialized already

**Comment by nfcampos** [comment]
Thanks so much for this @micahriggan , I've rebased this and pulling this in now

**Pull request merged**
