### PR TITLE
Add AWS Kendra Retriever

### PR DESCRIPTION
**Pull request by NickMandylas**
Adding new retriever for AWS Kendra.
Still in progress, rudimentary structure is in place.

Remaining Tasks:

- [x] Add new Retriever API (https://docs.aws.amazon.com/kendra/latest/dg/searching-retrieve.html) 
- [x] Documentation

### CODE REVIEW

**Comment by jacoblee93** [comment]
Hey @NickMandylas are you still working on this?

**Comment by NickMandylas** [comment]
Hey @jacoblee93 – Yep still working on it, apologise for the delay – got caught up with work. Will push completed integration by Friday this week.

**Comment by jacoblee93** [comment]
No worries and no rush! Just had someone ask about it.

**Comment by NickMandylas** [comment]
@jacoblee93 Integration for Kendra is completed with documentation.
Please let me know if there's anything else required :)

**Comment by jacoblee93** [comment]
Thank you! Just made some fairly large updates to retrievers/docs, so updated a few things there but looks good. Will merge tonight :)

**Pull request merged**
