### PR TITLE
fix(memory): throw error if no input/output key is specified and there are multiple keys

### PR DESCRIPTION
**Pull request by joaopcm**
@jopcmelo

This change fixes an issue that causes a lot of confusion when debugging Langchain applications. The issue is that when providing multiple keys to a memory instance, Langchain throws an error saying that an input/output key must be specified. The problem is that when the key conflict is related to the output scenario, the error message only mentions "input".

To fix and keep the code readable, I ended up separating the key-checking function from the objects and created another function called `getOutputValue` with a more descriptive message focused on output values, not input.

### CODE REVIEW

**Comment by joaopcm** [comment]
@jacoblee93, could you please review this PR?

**Comment by joaopcm** [comment]
cc @nfcampos

**Comment by joaopcm** [comment]
@jacoblee93 , do you think we can merge this one?

**Comment by jacoblee93** [comment]
Hi, apologies for the delay - wanted to make sure I looked at it very carefully since it's changing a base class.

**Comment by jacoblee93** [comment]
Thank you!

**Pull request merged**
