### PR TITLE
added a getter method for the memoryStream property on TimeWeightedVectorStoreRetriever

### PR DESCRIPTION
**Pull request by dylanintech**
# Added a getter method so that we can access the `memoryStream` property on instances of the `TimeWeightedVectorStoreRetriever` class
I'm trying to port over the following experimental abstractions from the python library: `GenerativeAgentMemory` and `GenerativeAgent`. I'm essentially translating the python classes outlined [here](https://python.langchain.com/en/latest/_modules/langchain/experimental/generative_agents/memory.html#GenerativeAgentMemory) and [here](https://python.langchain.com/en/latest/_modules/langchain/experimental/generative_agents/generative_agent.html#GenerativeAgent.Config) into typescript. However, I'm running into a problem when I want to access the `memoryStream` property on `memoryRetriever: TimeWeightedVectorStoreRetriever` as shown in the python implementation:
``` 
class GenerativeAgentMemory(BaseMemory) {
  #only relevant code shown

  memory_retriever: TimeWeightedVectorStoreRetriever
  """The retriever to fetch related memories."""

  def _get_topics_of_reflection(self, last_k: int = 50) -> List[str]:
        """Return the 3 most salient high-level questions about recent observations."""
        prompt = PromptTemplate.from_template(
            "{observations}\n\n"
            + "Given only the information above, what are the 3 most salient"
            + " high-level questions we can answer about the subjects in"
            + " the statements? Provide each question on a new line.\n\n"
        )
        observations = self.memory_retriever.memory_stream[-last_k:] #private property memory_stream is accessed
        observation_str = "\n".join([o.page_content for o in observations])
        result = self.chain(prompt).run(observations=observation_str)
        return self._parse_list(result)
}
```
However, when I try to implement the `getTopicsOfReflection` function in ts I get the following error because `memoryStream` is actually private:
`Property 'memoryStream' is private and only accessible within class TimeWeightedVectorStoreRetriever.ts(2341)
 `

This is why I've added `.getMemoryStream` to the `TimeWeightedVectorStoreRetriever` class -- so that we can access this property and work with generative agents in js/ts

my twitter by the way :) [@dxlantxch](https://twitter.com/dxlantxch)

### CODE REVIEW

**Comment by jacoblee93** [comment]
Hey @dylanintech, could you try rebasing this PR? Something went wonky with the diff and there's a whole bunch of other commits.

**Comment by jacoblee93** [comment]
Looks like this will be part of #1489 - will close this and merge as part of that one!

**Comment by dylanintech** [comment]
> Hey @dylanintech, could you try rebasing this PR? Something went wonky with the diff and there's a whole bunch of other commits.

Sorry, didn't see this! I know the issue is closed but is there still something weird going on with the diff?

**Comment by jacoblee93** [comment]
Screenshot 2023-06-01 at 2 49 15 PM

This is what it looks like on my end - I'm taking a look at your other one now!

**Comment by dylanintech** [comment]
Alright I think what happened is that as I had to pull a lot of changes from origin to get my branch up to speed with the most recent version of the main branch, so it bulked a ton of commits with the actual changes I made.

**Pull request closed without merging**
