### PR TITLE
Update metal - remove `.default`

### PR DESCRIPTION
**Pull request by Czechh**
- Metal SDK release `v3.0.0` removes pesky `.default`  https://github.com/getmetal/metal-ts/releases/tag/v3.0.0

### CODE REVIEW

**Comment by jacoblee93** [comment]
Hey @Czechh would you still like this merged?

**Comment by Czechh** [comment]
@jacoblee93  yes, I struggled a bit to get the types working

**Comment by jacoblee93** [comment]
> @jacoblee93 yes, I struggled a bit to get the types working

Ah, it was because you updated the `package.json` for the docs examples rather than the `devDependencies`. I made the required changes and will get this merged today!

**Comment by Czechh** [comment]
@jacoblee93 thank you! great catch 🙏

**Pull request merged**
