### PR TITLE
Add Upstash Redis cache

### LINKED ISSUE #1428: Feature request: Upstash Redis-based cache
LangChain already offers [Upstash Redis-Backed Chat Memory](https://js.langchain.com/docs/modules/memory/examples/upstash_redis), under `langchain/stores/message/upstash_redis`, in addition to [Redis-Backed Chat Memory](https://js.langchain.com/docs/modules/memory/examples/redis) under `langchain/stores/message/redis`. 

Would it be possible to create an Upstash Redis-based cache (presumably under `langchain/cache/upstash_redis`) to supplement the existing [Redis-based cache](https://js.langchain.com/docs/modules/models/llms/additional_functionality#caching-with-redis) under `langchain/cache/redis`?

### PR DESCRIPTION
**Pull request by ap-1**
This PR adds an Upstash Redis-based cache under `langchain/cache/upstash_redis` to supplement the existing [Redis-based cache](https://js.langchain.com/docs/modules/models/llms/additional_functionality#caching-with-redis) under `langchain/cache/redis`. This adds parity with `langchain/stores/message/redis` and `langchain/stores/message/upstash_redis`.

Closes #1428

### CODE REVIEW

**Comment by jasan-s** [comment]
Is semantic cache possible with this integration?

**Comment by ap-1** [comment]
> Is semantic cache possible with this integration? E.g evaluate hits based on semantic similarity.

Currently, this is a 1:1 copy of the [redis-based cache](https://github.com/hwchase17/langchainjs/blob/main/langchain/src/cache/redis.ts)

**Comment by jasan-s** [comment]
Let's get this merged 🙂

**Comment by jacoblee93** [comment]
Thanks for this! Tiny fix on examples, otherwise LGTM and will aim to have it merged with tomorrow's release.

**Comment by Kevin-Liu-01** [comment]
LGTM

**Pull request merged**
