### PR TITLE
Add size parameter to elastic search query #2229

### LINKED ISSUE #2229: ElasticVectorSearch - search similarity without possibility to pass size to query
Add the possibility to pass the size parameter in the similarity searchs, eg: Class ElasticVectorSearch

It's always returning 10 documents (elastic's default conf)

```
const result = await this.client.search({
        ***size: value***,
        index: this.indexName,
        knn: {
            field: "embedding",
            query_vector: query,
            filter: this.buildMetadataTerms(filter),
            k,
            num_candidates: this.candidates,
        },
    });
```

### PR DESCRIPTION
**Pull request by mEliehl**
Passing k as size on elastic vector store
Also include test to validate the length

Fixes #2229

### CODE REVIEW

**Comment by jacoblee93** [comment]
Seems good to me - CC @ezimuel!

**Comment by jacoblee93** [comment]
@mEliehl can you run `yarn format` please?

**Comment by ezimuel** [comment]
@jacoblee93 LGTM, thanks.

**Comment by jacoblee93** [comment]
Thank you!

**Pull request merged**
