### PR TITLE
Add GoogleSearchAPIWrapper

### PR DESCRIPTION
**Pull request by sajadghawami**
Tried to stay very close to the [implementation](https://python.langchain.com/en/latest/modules/agents/tools/examples/google_search.html) of the python package.

The following env variables are needed:

`GOOGLE_CSE_ID`
`GOOGLE_API_KEY`

### CODE REVIEW

**Comment by sajadghawami** [comment]
@nfcampos 

Just updated this MR.
I can't see why the deployment is failing, but my guess is that the new `envs` are missing.

If there is anything else missing, please let me know and i ll happy to add it so that we can merge this asap :)

Thank you!

**Comment by baobo5625** [comment]
@sajadghawami do we have any updates per this MR

**Comment by sajadghawami** [comment]
@baobo5625 

unfortunately not yet!

**Comment by nfcampos** [comment]
Hi @sajadghawami sorry for the delay here, in the JS package we usually implement tools as subclasses of the base `Tool` class. Which means also giving it a name and description, as well as ensuring it returns a string, not an array as you have here. Can you make those changes?

**Comment by sajadghawami** [comment]
@nfcampos 

sure! no worries :) ... i ll take a look at it and will let u know asap

**Comment by jacoblee93** [comment]
Closing now that #1260 is merged.

**Pull request closed without merging**
