### PR TITLE
Add finishReason to openai generationInfo

### LINKED ISSUE #1556: Neither .call nor .generate return full response from OpenAi/AzureOpenAi
I need entire response from the provider I use. From the source code of openai.js it is seen that it only returns token information and the generated message skipping all other datapoints
image

Lets return the rest of the response in a dedicated field, 'metadata' for instance?

### PR DESCRIPTION
**Pull request by davidtom**
This small change adds `finishReason` to the `generationInfo` object of the OpenAI `_generate` method's `output`. This would be a huge help for us when using langchainjs, and it seems like others have requested it as well.

Fixes #1556 and #2099

### CODE REVIEW

**Comment by jacoblee93** [comment]
Hey @davidtom! I'm aiming to get #2389 merged this week - will work this into that PR!

**Comment by jacoblee93** [comment]
I think right now it'd be easier to lift if that's ok with you? There might be a rebase or two in the future there 🙈

**Comment by jacoblee93** [comment]
Sounds good! Put a bunch of work into the other PR today - am planning to merge by Friday's release.

**Comment by buttercoding** [comment]
Can you provide an example of usage?

**Comment by matheuslemke** [comment]
@buttercoding here is an example: https://github.com/langchain-ai/langchainjs/issues/2099#issuecomment-1761466796

**Pull request merged**
